### PR TITLE
Switch to ruff for lint and format

### LINKED ISSUE #1558: Switch to ruff for formatting and linting

### PR DESCRIPTION
**Pull request by sainak**
## Proposed Changes

- use ruff for formatting and linting
- update ci
- update precommit hooks
- cleanup gitignore

### Associated Issue

- closes #1558

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

### CODE REVIEW

**Comment by vigneshhari** [comment]
Make sure you add some make commands that lint currently staged and all files ( both with and without docker )

**Review by vigneshhari — APPROVED** [review]

**Comment by sainak** [comment]
TODO:

- [x] reverify the rules
- [x] cleanup vscode settings

**Comment by bodhish** [comment]
@sainak if you are not planing to work on it, lets close the PR

**Comment by sainak** [comment]
> @sainak if you are not planing to work on it, lets close the PR

I'll finish this up by tomorrow, waiting for #2449

**Review by vigneshhari — APPROVED** [review]

**Pull request merged**
